version: '3'
services:
  api-relatorio:
    build:
      context: .
      args:
        - BUILD_CONFIGURATION=Debug
      dockerfile: Dockerfile
    image: hackathon-soat1-grp13-relatorio:latest
    restart: on-failure    
    ports:
      - "5272:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=User ID=fiap;Password=SenhaLocalRelatorio;Host=postgres-db-relatorio;Port=5434;Database=hackathonrelatorio;Pooling=true;
    depends_on:
      postgres-db-relatorio:
        condition: service_healthy

  postgres-db-relatorio:  
    hostname: postgres-compose
    image: postgres
    environment:
      POSTGRES_PASSWORD: "SenhaLocalRelatorio"
      POSTGRES_USER: fiap
      POSTGRES_DB: hackathonrelatorio
    ports:
      - "15436:5433"
    volumes:
      - hackathon-soat1-grp13-db-data-relatorio:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  hackathon-soat1-grp13-db-data-relatorio: