name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get-version.outputs.version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get version from URL
      id: get-version
      run: echo "::set-output name=version::$(curl -s https://devcm.com.br/versao/?projeto=Hackathon-Relatorio)"

    - name: Set up version
      run: echo "VERSION=${{ steps.get-version.outputs.version }}" >> $GITHUB_ENV

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t christiandmelo/hackathon-soat1-grp13-relatorio:${{ env.VERSION }} .

    - name: Push Docker image
      run: docker push christiandmelo/hackathon-soat1-grp13-relatorio:${{ env.VERSION }}

  update-service:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: us-west-2
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      env:
        VERSION: ${{needs.build-and-push.outputs.VERSION}}
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: deploy/task-definition.json
        container-name: producao-api
        image: christiandmelo/hackathon-soat1-grp13-relatorio:${{env.VERSION}}
    
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: producao-service
        cluster: soat1-grp13-hackathon
        wait-for-service-stability: true